extension:
    dubbo:
        scan: com.wayneleo.quickstart
        application.name: provider
        registry.address: zookeeper://127.0.0.1:2182
        protocol.name: dubbo
        protocol.port: 28080
        module.name: QuickStart
        consumer.timeout: 1000
        consumer.retries: 5