
mgmt:
    secret: 4jg75AbeA3Saz3RzAtta

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/information_schema?roundRobinLoadBalance=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 123456
        max-active: 10
        max-idle: 8 
        min-idle: 8 
        initial-size: 2
        validation-query: select 1 from dual
        test-on-borrow: false
        test-while-idle: true
        time-between-eviction-runs-millis: 7200
        jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=5000)
    jpa:
        show-sql: true
        hibernate.ddl-auto: none
        properties.hibernate.dialect: org.hibernate.dialect.MySQLInnoDBDialect

cache:
    duration: 30000

threadPool:
    corePoolSize: 2
    maxPoolSize: 10
    keepAliveTime: 60

